import yaml
import os
import glob

"""Parse config"""
configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

"""Rules"""
include: os.path.join("rules", "0.preflight.smk")
include: os.path.join("rules", "1.qc.smk")
include: os.path.join("rules", "2.host_contamination.smk")
#include: os.path.join("rules", "3.co-assembly.smk")
include: os.path.join("rules", "3.individual_assembly.smk")
include: os.path.join("rules", "4.mapping.smk")
include: os.path.join("rules", "4.metabat2.smk")

"""Mark target rules"""
target_rules = []
def targetRule(fn):
    assert fn.__name__.startswith('__')
    target_rules.append(fn.__name__[2:])
    return fn

"""
Defining the targets dictionary
"""
targets ={'qc':[], 'assemble':[], 'binning':[]}

targets['qc'] = []
if config['args']['sequencing'] == 'paired':
    for sample in sample_names:
        targets['qc'].append(expand(os.path.join(dir_fastp,"{sample}.stats.html"), sample=sample))
        targets['qc'].append(expand(os.path.join(dir_hostcleaned,"{sample}_R1.hostcleaned.fastq.gz"), sample=sample))

if config['args']['sequencing'] == 'paired':
    ## For coassembly targets
    #targets['assemble'].append(os.path.join(dir_assembly,"coassembly.megahit.contigs.fa"))
    #targets['assemble'].append(os.path.join(dir_assembly,"quast_report.txt"))

    ## For individual assembly targets
    for sample in sample_names:
        targets['assemble'].append(os.path.join(dir_assembly,"{sample}.megahit.contigs.fa").format(sample=sample))
        targets['assemble'].append(os.path.join(dir_assembly, "{sample}_quast_output", "report.txt").format(sample=sample))

if config['args']['sequencing'] == 'paired':
    for sample in sample_names:
        targets['binning'].append(os.path.join(dir_binning, "{sample}_index.mmi").format(sample=sample))
        targets['binning'].append(os.path.join(dir_binning, "{sample}_bam", "done.txt").format(sample=sample))
        targets['binning'].append(os.path.join(dir_binning, "{sample}_metabat2_bins", "done.txt").format(sample=sample))

@targetRule
rule all:
    input:
        targets['qc'],
        targets['assemble'],
        targets['binning']

@targetRule
rule qc:
    input:
        targets['qc']

@targetRule
rule assembly:
    input:
        targets['assemble']

@targetRule
rule binning:
    input:
        targets['binning']