import yaml
import os
import glob

"""Parse config"""
configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

"""Rules"""
include: os.path.join("rules", "0.preflight.smk")
include: os.path.join("rules", "1.qc.smk")
include: os.path.join("rules", "2.host_contamination.smk")
include: os.path.join("rules", "Final_QC.smk")
#include: os.path.join("rules", "3.co-assembly.smk")
#include: os.path.join("rules", "3.individual_assembly.smk")
#include: os.path.join("rules", "4.mapping.smk")
#include: os.path.join("rules", "5.metabat2.smk")
#include: os.path.join("rules", "6.bins_quality.smk")
#include: os.path.join("rules", "7.drep.smk")
#include: os.path.join("rules", "Final_binning.smk")

#############################################
# AFTER sample detection logic for maping 
#############################################

sample_names = list(paired_reads.keys())
N_SAMPLES = len(sample_names)

THRESHOLD = config['args'].get('mapping_threshold', 100)

print(f"Detected {N_SAMPLES} samples")

if N_SAMPLES <= THRESHOLD:
    print("Using all-vs-all mapping strategy")
    include: os.path.join("rules", "mapping_all_2_all.smk")
else:
    print("Using simka mapping strategy")
    include: os.path.join("rules", "mapping_simka.smk")



"""Mark target rules"""
target_rules = []
def targetRule(fn):
    assert fn.__name__.startswith('__')
    target_rules.append(fn.__name__[2:])
    return fn

"""
Defining the targets dictionary
"""
targets ={'qc':[], 'host':[], 'assemble':[], 'binning':[]}

if config['args']['sequencing'] == 'paired':
    for sample in sample_names:
        targets['qc'].append(expand(os.path.join(dir_fastp,"{sample}.stats.html"), sample=sample)),
        targets['qc'].append(expand(os.path.join(dir_hostcleaned,"{sample}_temp.bam"), sample=sample)),
        targets['qc'].append(expand(os.path.join(dir_hostcleaned,"{sample}_bamstats.txt"), sample=sample)),
        targets['qc'].append(expand(os.path.join(dir_hostcleaned,"{sample}_R1.hostcleaned.fastq.gz"), sample=sample)),
        targets['qc'].append(expand(os.path.join(dir_hostcleaned,"{sample}_R2.hostcleaned.fastq.gz"), sample=sample)),
        targets['qc'].append(expand(os.path.join(dir_reports,"QC","{sample}_host_qc_report.txt"), sample=sample)),
        targets['qc'].append(os.path.join(dir_reports, "final_host_qc_summary.txt"))


if config['args']['sequencing'] == 'paired':
    ## For coassembly targets
    #targets['assemble'].append(os.path.join(dir_assembly,"coassembly.megahit.contigs.fa"))
    #targets['assemble'].append(os.path.join(dir_assembly,"quast_report.txt"))

    ## For individual assembly targets
    for sample in sample_names:
        targets['assemble'].append(os.path.join(dir_assembly,"{sample}.megahit.contigs.fa").format(sample=sample))
        targets['assemble'].append(os.path.join(dir_assembly, "{sample}_quast_output", "report.txt").format(sample=sample))

if config['args']['sequencing'] == 'paired':
    for sample in sample_names:
        targets['binning'].append(os.path.join(dir_binning, "{sample}_index.mmi").format(sample=sample))
        targets['binning'].append(os.path.join(dir_binning, "{sample}_bam", "done.txt").format(sample=sample))
        targets['binning'].append(os.path.join(dir_binning, "all_metabat2_bins", "done.txt"))
        targets['binning'].append(os.path.join(dir_binning, "checkm2_output", "quality_report.tsv"))
        targets['binning'].append(os.path.join(dir_binning, "gtdbtk_output", "done.txt"))
        targets['binning'].append(os.path.join(dir_reports, "checkm2_quality_reports.tsv"))
        targets['binning'].append(os.path.join(dir_reports, "gtdbtk_bac120_summary.tsv"))

@targetRule
rule all:
    input:
        targets['qc'],
        targets['host'],
        targets['assemble'],
        targets['binning']

@targetRule
rule qc:
    input:
        targets['qc']
    
@targetRule
rule assembly:
    input:
        targets['assemble']

@targetRule
rule binning:
    input:
        targets['binning']
