resources:
  smalljob:
    cpu: 8
    mem: 16000
    time: 480
  bigjob:
    cpu: 32
    mem: 64000
    time: 480

params:
  #gene-predict: 'prodigal-gv' #to test alternate codons, uncomment this

args:
  #output: "sphae.out"

  #For now I will use environmental variables like below to define the database paths
  #Once I have a stable build, might be worth considering how to download them automatically
  #vv_db: $VVDB
