resources:
  smalljob:
    cpu: 2
    mem: 16000
    time: 240
  assemblyjob:
    cpu: 64
    mem: 256000
    time: 2880
  bigjob:
    cpu: 32
    mem: 64000
    time: 480

args:
  input: 
  extn: 
  host_seq: 
  output: 
  sequencing: 
  configfile: 
  temp_dir: 

databases:
  checkm_db: /users/bnalaga1/scratch/reference_db/CheckM2_database
  gtdbtk_db: /users/bnalaga1/scratch/reference_db/release226/

extra_db:
  mitogenome: /users/bnalaga1/scratch/reference_db/CM009947_ref_mt.fasta