resources:
  smalljob:
    threads: 2
    mem_mb: 16000
    runtime: 240
  highmemjob:
    threads: 4
    mem_mb: 250000
    runtime: 480
  assemblyjob:
    threads: 16
    mem_mb: 250000
    runtime: 480
  bigjob:
    threads: 8
    mem_mb: 64000
    runtime: 480
  big_longjob:
    threads: 8
    mem_mb: 64000
    runtime: 1440
  long_shortjob:
    threads: 8
    mem_mb: 16000
    runtime: 720
  longjob:
    threads: 8
    mem_mb: 16000
    runtime: 1440
  small_longjob:
    threads: 2
    mem_mb: 16000
    runtime: 1440
  medium:
    threads: 8
    mem_mb: 32000
    runtime: 480
  gpujob:
    threads: 2
    mem_mb: 16000
    runtime: 300
  assembly_longjob:
    threads: 16
    mem_mb: 250000
    runtime: 1440

  
args:
  input: 
  extn: 
  host_seq: 
  output: 
  sequencing: 
  configfile: 
  temp_dir:
  mapping_threshold: 50 

databases:
  checkm2_db: /work/FAC/FBM/DMF/pengel/general_data/common_databases/checkm2/CheckM2_database
  gtdbtk_db: /work/FAC/FBM/DMF/pengel/general_data/common_databases/gtdb/release232
  checkm_db: /work/FAC/FBM/DMF/pengel/general_data/common_databases/checkm
  bakta_db: /work/FAC/FBM/DMF/pengel/general_data/common_databases/bakta_download/db